# Generated by Django 5.2.4 on 2025-11-12 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fileupload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='encrypted_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='private_key',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='public_key',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static\\files'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='original_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
